#Copyright (C) 2015 xent
#Project is distributed under the terms of the GNU General Public License v3.0

ifeq ($(CONFIG_DRIVERS_RGB_LED),y)
  CSOURCES += drivers/rgb_led.c
endif

ifeq ($(CONFIG_DRIVERS_SOFTWARE_PWM),y)
  CSOURCES += drivers/software_pwm.c
endif
