#!/usr/bin/env python3

import argparse
import math
import os
import textwrap

TABLE_SIZE = 64

def make_table(adc_max, adc_res, b_value, r_external, r_thermistor, lowside=False):
    step = adc_max // TABLE_SIZE
    kelvin_offset = 273.15
    t_ref = 25.0 + kelvin_offset
    lsb_offset = 2.0 / adc_res

    raw = 0
    output = []
    while raw <= adc_max:
        level = raw / (adc_max - 1)
        if lowside:
            level = 1.0 - level
        if level < lsb_offset:
            level = lsb_offset
        elif level > 1.0 - lsb_offset:
            level = 1.0 - lsb_offset
        r_actual = (r_external * level) / (1.0 - level)
        t = 1.0 / (1.0 / t_ref - math.log(r_thermistor / r_actual) / b_value)

        output.append(round((t - kelvin_offset) * 100.0))
        raw += step
    return output

def generate_header(name, suffix):
    output = textwrap.dedent(f'''\
        /*
         * {name}.h
         * Generated by make_ntc_table.py
         */

        #ifndef {name.upper()}_H_
        #define {name.upper()}_H_
        /*----------------------------------------------------------------------------*/
        #include <xcore/helpers.h>
        #include <stdint.h>
        /*----------------------------------------------------------------------------*/
        BEGIN_DECLS

        int32_t ntcRawToTemperature{suffix}(uint16_t);
        uint16_t ntcTemperatureToRaw{suffix}(int32_t);

        END_DECLS
        /*----------------------------------------------------------------------------*/
        #endif /* {name.upper()}_H_ */
        ''')
    return output

def generate_source(table, name, suffix):
    output = textwrap.dedent(f'''\
        /*
         * {name}.c
         * Generated by make_ntc_table.py
         */

        #include <dpm/sensors/thermistor_ntc.h>
        #include <assert.h>
        /*----------------------------------------------------------------------------*/
        static const int16_t TEMPERATURE_TABLE_{suffix}[] = {{
        ''')

    i = 0
    while i < len(table):
        count = min(8, len(table) - i)
        output += '    ' + ', '.join(f'{value:6d}' for value in table[i:i + count])
        i += count
        if i < len(table):
            output += ','
        output += '\n'

    output += textwrap.dedent(f'''\
        }};
        static_assert(ARRAY_SIZE(TEMPERATURE_TABLE_{suffix}) == NTC_TABLE_SIZE,
            "Incorrect table size");
        /*----------------------------------------------------------------------------*/
        int32_t ntcRawToTemperature{suffix}(uint16_t value)
        {{
            return ntcRawToTemperature(TEMPERATURE_TABLE_{suffix}, value);
        }}
        /*----------------------------------------------------------------------------*/
        uint16_t ntcTemperatureToRaw{suffix}(int32_t temperature)
        {{
            return ntcTemperatureToRaw(TEMPERATURE_TABLE_{suffix}, temperature);
        }}
        ''')
    return output

def make_resistor_suffix(r):
    if r % 1000 == 0:
        suffix = f'{r // 1000}k'
    elif r % 100 == 0:
        suffix = f'{r // 1000}k{(r % 1000) // 100}'
    else:
        suffix = f'{r // 1000}k{(r % 1000) // 10}'
    return suffix

def main():
    args = argparse.ArgumentParser()
    args.add_argument('-a', dest='resolution', help='ADC resolution in bits',
                      type=int, default=None)
    args.add_argument('-j', dest='justify', help='ADC justify left or right',
                      type=str, default='right')
    args.add_argument('-b', dest='beta', help='beta value',
                      type=int, default=None)
    args.add_argument('-l', dest='lowside', help='thermistor is in low side',
                      default=False, action='store_true')
    args.add_argument('-n', dest='name', help='file name in generated code',
                      type=str, default='')
    args.add_argument('-o', dest='output', help='output directory',
                      type=str, default='')
    args.add_argument('-r', dest='r_external', help='external resistor value in Ohm',
                      type=int, default=None)
    args.add_argument('-s', dest='suffix', help='suffix for functions',
                      type=str, default='')
    args.add_argument('-t', dest='r_thermistor', help='thermistor value in Ohm',
                      type=int, default=None)
    args.add_argument('--header', dest='header', help='generate header file',
                      default=False, action='store_true')
    args.add_argument('--source', dest='source', help='generate source file',
                      default=False, action='store_true')

    options = args.parse_args()

    if options.beta is None or options.r_external is None or options.r_thermistor is None:
        raise ValueError()
    if options.justify not in ('left', 'right'):
        raise ValueError()
    if options.resolution is None or options.resolution < 8 or options.resolution > 16:
        raise ValueError()
    if not options.header and not options.source:
        options.header = options.source = True

    adc_max = 1 << options.resolution if options.justify == 'left' else 1 << 16
    adc_res = 1 << options.resolution

    if options.name:
        name = options.name
    else:
        name = 'thermistor_ntc_' + make_resistor_suffix(options.r_thermistor)

    if options.suffix:
        suffix = options.suffix
    else:
        suffix = make_resistor_suffix(options.r_thermistor).upper()

    table = make_table(
        adc_max=adc_max,
        adc_res=adc_res,
        b_value=options.beta,
        r_external=options.r_external,
        r_thermistor=options.r_thermistor,
        lowside=options.lowside
    )

    if options.header:
        text = generate_header(name, suffix)
        if options.output:
            with open(os.path.join(options.output, name) + '.h', 'wb') as output_file:
                output_file.write(text.encode())
        else:
            print(text, end='')
    if options.source:
        text = generate_source(table, name, suffix)
        if options.output:
            with open(os.path.join(options.output, name) + '.c', 'wb') as output_file:
                output_file.write(text.encode())
        else:
            print(text, end='')

if __name__ == '__main__':
    main()
